//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTapChi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuChinhSua
    {
        public int ID { get; set; }
        public Nullable<int> IDTapChiBaiViet { get; set; }
        public string NoiDungCu { get; set; }
        public string NoiDungMoi { get; set; }
        public Nullable<System.DateTime> NgayChinhSua { get; set; }
        public Nullable<int> VongPhanBien { get; set; }
        public Nullable<int> LanChinhSua { get; set; }
        public string GhiChu { get; set; }
        public string DuongDanFile { get; set; }
        public Nullable<int> IDNguoiChinhSua { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual TapChiBaiViet TapChiBaiViet { get; set; }
    }
}
