//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTapChi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XuatBan
    {
        public int IDXuatBan { get; set; }
        public string SoTapChi { get; set; }
        public System.DateTime NgayXuatBan { get; set; }
        public int IDTapChiBaiViet { get; set; }
        public int IDBienTapVien { get; set; }
        public Nullable<int> IDSoTapChi { get; set; }
    
        public virtual BienTapVien BienTapVien { get; set; }
        public virtual SoTapChi SoTapChi1 { get; set; }
        public virtual TapChiBaiViet TapChiBaiViet { get; set; }
    }
}
